// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 1. 定義 PLC 的選單
  plcSidebar: [
    'intro',            // 三菱Q系列PLC簡介
    '00-PLC型錄',       // 三菱Q系列PLC型錄
    '01-指令說明書',
    '02-CPU說明書',
    '03-IO模組',
    {
      type: 'category',
      label: '4. CC-Link說明書',
      items: [{type: 'autogenerated', dirName: '04-CC-Link說明書'}],
    },
    {
      type: 'category',
      label: '5. 類比模組',
      items: [{type: 'autogenerated', dirName: '05-類比模組'}],
    },
  ],

  // 2. 定義變頻器的選單 (只抓取 inverter 資料夾內的檔案)
  inverterSidebar: [
    {
      type: 'autogenerated',
      dirName: 'inverter', 
    },
  ],
};

export default sidebars;