// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 1. 定義 PLC 的選單
  plcSidebar: [
    'intro',            // 對應 intro.md
    'PLC型錄',          // Docusaurus 會自動把 00- 去掉變成 ID
    '指令說明書',        // 自動把 01- 去掉
    'CPU說明書',        // 自動把 02- 去掉
    'IO模組',           // 自動把 03- 去掉
    {
      type: 'category',
      label: '4. CC-Link說明書',
      // dirName 必須指向實體的資料夾名稱
      items: [{type: 'autogenerated', dirName: '04-CC-Link說明書'}],
    },
    {
      type: 'category',
      label: '5. 類比模組',
      // dirName 必須指向實體的資料夾名稱
      items: [{type: 'autogenerated', dirName: '05-類比模組'}],
    },
  ],
  // 2. 定義MCU的選單
  mcuSidebar: [
    {
      type: 'autogenerated',
      dirName: 'mcu', // 自動抓取 docs/mcu 資料夾
    },
  ],
  // 3. 定義變頻器的選單
  inverterSidebar: [
    {
      type: 'autogenerated',
      dirName: 'inverter', 
    },
  ],
};

export default sidebars;